<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZHZ2IdW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZHZ2IdW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZHZ2IdW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZHZ2IdW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZHZ2IdW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZHZ2IdW',
    'container.build_id' => '84e3d71d',
    'container.build_time' => 1611790194,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZHZ2IdW');
