<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRaEetZu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRaEetZu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRaEetZu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRaEetZu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRaEetZu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RaEetZu',
    'container.build_id' => '609a5e45',
    'container.build_time' => 1612147830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRaEetZu');
